package nats

// AUTOGENERATED FILE - DO NOT EDIT.
//
// This file has been automatically generated by FrankenPHP extension generator
// and should not be edited as it will be overwritten when running the
// extension generator again.
//
// You may edit the file and remove this comment if you plan to manually maintain
// this file going forward.

// #include <stdlib.h>
// #include "nats.h"
import "C"
import (
	_ "runtime/cgo"
	"unsafe"

	"github.com/dunglas/frankenphp"
)

func init() {
	frankenphp.RegisterExtension(unsafe.Pointer(&C.nats_module_entry))
}

//export go_connect
func go_connect(name *C.zend_string, servers *C.zend_array, username *C.zend_string, password *C.zend_string, token *C.zend_string, credsFile *C.zend_string, nkeyFile *C.zend_string, useTLS bool, timeoutNs int64, reconnectAttempts int64, reconnectWaitNs int64, pingIntervalNs int64, maxPingsOut int64) {
	natsConnect(name, servers, username, password, token, credsFile, nkeyFile, useTLS, timeoutNs, reconnectAttempts, reconnectWaitNs, pingIntervalNs, maxPingsOut)
}

//export go_close
func go_close(name *C.zend_string) {
	natsClose(name)
}

//export go_isConnected
func go_isConnected(name *C.zend_string) bool {
	return natsIsConnected(name)
}

//export go_flush
func go_flush(name *C.zend_string, timeoutNs int64) {
	natsFlush(name, timeoutNs)
}

//export go_stats
func go_stats(name *C.zend_string) unsafe.Pointer {
	return natsStats(name)
}

//export go_publish
func go_publish(name *C.zend_string, subject *C.zend_string, data *C.zend_string, headers *C.zend_array) {
	natsPublish(name, subject, data, headers)
}

//export go_request
func go_request(name *C.zend_string, subject *C.zend_string, data *C.zend_string, timeoutNs int64) unsafe.Pointer {
	return natsRequest(name, subject, data, timeoutNs)
}

//export go_subscribe
func go_subscribe(name *C.zend_string, subject *C.zend_string, queue *C.zend_string) unsafe.Pointer {
	return natsSubscribe(name, subject, queue)
}

//export go_unsubscribe
func go_unsubscribe(subID *C.zend_string) {
	natsUnsubscribe(subID)
}

//export go_nextMessage
func go_nextMessage(subID *C.zend_string, timeoutNs int64) unsafe.Pointer {
	return natsNextMessage(subID, timeoutNs)
}

//export go_subscriptionValid
func go_subscriptionValid(subID *C.zend_string) bool {
	return natsSubscriptionValid(subID)
}
