// AUTOGENERATED FILE - DO NOT EDIT.
//
// This file has been automatically generated by FrankenPHP extension generator
// and should not be edited as it will be overwritten when running the
// extension generator again.
//
// You may edit the file and remove this comment if you plan to manually maintain
// this file going forward.

#ifndef _NATS_H
#define _NATS_H

#include <php.h>
#include <stdint.h>

extern zend_module_entry nats_module_entry;


/* User defined constants */
#define NANOSECOND 1
#define MICROSECOND 1000
#define MILLISECOND 1000000
#define SECOND 1000000000
#define MINUTE 60000000000

#endif
