// AUTOGENERATED FILE - DO NOT EDIT.
//
// This file has been automatically generated by FrankenPHP extension generator
// and should not be edited as it will be overwritten when running the
// extension generator again.
//
// You may edit the file and remove this comment if you plan to manually maintain
// this file going forward.

#include <php.h>
#include <Zend/zend_API.h>
#include <Zend/zend_hash.h>
#include <Zend/zend_types.h>
#include <stddef.h>

#include "nats.h"
#include "nats_arginfo.h"
#include "_cgo_export.h"


PHP_MINIT_FUNCTION(nats) {
    
        REGISTER_NS_LONG_CONSTANT("Abderrahim\\Nats", "NANOSECOND", 1, CONST_CS | CONST_PERSISTENT);
        REGISTER_NS_LONG_CONSTANT("Abderrahim\\Nats", "MICROSECOND", 1000, CONST_CS | CONST_PERSISTENT);
        REGISTER_NS_LONG_CONSTANT("Abderrahim\\Nats", "MILLISECOND", 1000000, CONST_CS | CONST_PERSISTENT);
        REGISTER_NS_LONG_CONSTANT("Abderrahim\\Nats", "SECOND", 1000000000, CONST_CS | CONST_PERSISTENT);
        REGISTER_NS_LONG_CONSTANT("Abderrahim\\Nats", "MINUTE", 60000000000, CONST_CS | CONST_PERSISTENT);
    return SUCCESS;
}

zend_module_entry nats_module_entry = {STANDARD_MODULE_HEADER,
                                         "nats",
                                         ext_functions,             /* Functions */
                                         PHP_MINIT(nats),  /* MINIT */
                                         NULL,                      /* MSHUTDOWN */
                                         NULL,                      /* RINIT */
                                         NULL,                      /* RSHUTDOWN */
                                         NULL,                      /* MINFO */
                                         "1.0.0",                   /* Version */
                                         STANDARD_MODULE_PROPERTIES};
PHP_FUNCTION(Abderrahim_Nats_connect)
{
    zend_string *name = NULL;
    zend_array *servers = NULL;
    zend_string *username = NULL;
    zend_string *password = NULL;
    zend_string *token = NULL;
    zend_string *credsFile = NULL;
    zend_string *nkeyFile = NULL;
    zend_bool tls = false;
    zend_long timeout = 2000000000;
    zend_long reconnectAttempts = 60;
    zend_long reconnectWait = 2000000000;
    zend_long pingInterval = 120000000000;
    zend_long maxPingsOut = 2;
    ZEND_PARSE_PARAMETERS_START(2, 13)
        Z_PARAM_STR(name)
        Z_PARAM_ARRAY_HT(servers)
        Z_PARAM_OPTIONAL
        Z_PARAM_STR(username)
        Z_PARAM_STR(password)
        Z_PARAM_STR(token)
        Z_PARAM_STR(credsFile)
        Z_PARAM_STR(nkeyFile)
        Z_PARAM_BOOL(tls)
        Z_PARAM_LONG(timeout)
        Z_PARAM_LONG(reconnectAttempts)
        Z_PARAM_LONG(reconnectWait)
        Z_PARAM_LONG(pingInterval)
        Z_PARAM_LONG(maxPingsOut)
    ZEND_PARSE_PARAMETERS_END();
    go_connect(name, servers, username, password, token, credsFile, nkeyFile, (int) tls, (long) timeout, (long) reconnectAttempts, (long) reconnectWait, (long) pingInterval, (long) maxPingsOut);
}

PHP_FUNCTION(Abderrahim_Nats_close)
{
    zend_string *name = NULL;
    ZEND_PARSE_PARAMETERS_START(1, 1)
        Z_PARAM_STR(name)
    ZEND_PARSE_PARAMETERS_END();
    go_close(name);
}

PHP_FUNCTION(Abderrahim_Nats_isConnected)
{
    zend_string *name = NULL;
    ZEND_PARSE_PARAMETERS_START(1, 1)
        Z_PARAM_STR(name)
    ZEND_PARSE_PARAMETERS_END();
    int result = go_isConnected(name);
    RETURN_BOOL(result);
}

PHP_FUNCTION(Abderrahim_Nats_flush)
{
    zend_string *name = NULL;
    zend_long timeout = 5000000000;
    ZEND_PARSE_PARAMETERS_START(1, 2)
        Z_PARAM_STR(name)
        Z_PARAM_OPTIONAL
        Z_PARAM_LONG(timeout)
    ZEND_PARSE_PARAMETERS_END();
    go_flush(name, (long) timeout);
}

PHP_FUNCTION(Abderrahim_Nats_stats)
{
    zend_string *name = NULL;
    ZEND_PARSE_PARAMETERS_START(1, 1)
        Z_PARAM_STR(name)
    ZEND_PARSE_PARAMETERS_END();
    zend_array *result = go_stats(name);
    if (result) {
        RETURN_ARR(result);
    }

	RETURN_EMPTY_ARRAY();
}

PHP_FUNCTION(Abderrahim_Nats_publish)
{
    zend_string *name = NULL;
    zend_string *subject = NULL;
    zend_string *data = NULL;
    zend_array *headers = NULL;
    ZEND_PARSE_PARAMETERS_START(3, 4)
        Z_PARAM_STR(name)
        Z_PARAM_STR(subject)
        Z_PARAM_STR(data)
        Z_PARAM_OPTIONAL
        Z_PARAM_ARRAY_HT(headers)
    ZEND_PARSE_PARAMETERS_END();
    go_publish(name, subject, data, headers);
}

PHP_FUNCTION(Abderrahim_Nats_request)
{
    zend_string *name = NULL;
    zend_string *subject = NULL;
    zend_string *data = NULL;
    zend_long timeout = 1000000000;
    ZEND_PARSE_PARAMETERS_START(3, 4)
        Z_PARAM_STR(name)
        Z_PARAM_STR(subject)
        Z_PARAM_STR(data)
        Z_PARAM_OPTIONAL
        Z_PARAM_LONG(timeout)
    ZEND_PARSE_PARAMETERS_END();
    zend_array *result = go_request(name, subject, data, (long) timeout);
    if (result) {
        RETURN_ARR(result);
    }

	RETURN_NULL();
}

PHP_FUNCTION(Abderrahim_Nats_subscribe)
{
    zend_string *name = NULL;
    zend_string *subject = NULL;
    zend_string *queue = NULL;
    ZEND_PARSE_PARAMETERS_START(2, 3)
        Z_PARAM_STR(name)
        Z_PARAM_STR(subject)
        Z_PARAM_OPTIONAL
        Z_PARAM_STR(queue)
    ZEND_PARSE_PARAMETERS_END();
    zend_string *result = go_subscribe(name, subject, queue);
    if (result) {
        RETURN_STR(result);
    }

	RETURN_EMPTY_STRING();
}

PHP_FUNCTION(Abderrahim_Nats_unsubscribe)
{
    zend_string *subId = NULL;
    ZEND_PARSE_PARAMETERS_START(1, 1)
        Z_PARAM_STR(subId)
    ZEND_PARSE_PARAMETERS_END();
    go_unsubscribe(subId);
}

PHP_FUNCTION(Abderrahim_Nats_nextMessage)
{
    zend_string *subId = NULL;
    zend_long timeout = 5000000000;
    ZEND_PARSE_PARAMETERS_START(1, 2)
        Z_PARAM_STR(subId)
        Z_PARAM_OPTIONAL
        Z_PARAM_LONG(timeout)
    ZEND_PARSE_PARAMETERS_END();
    zend_array *result = go_nextMessage(subId, (long) timeout);
    if (result) {
        RETURN_ARR(result);
    }

	RETURN_NULL();
}

PHP_FUNCTION(Abderrahim_Nats_subscriptionValid)
{
    zend_string *subId = NULL;
    ZEND_PARSE_PARAMETERS_START(1, 1)
        Z_PARAM_STR(subId)
    ZEND_PARSE_PARAMETERS_END();
    int result = go_subscriptionValid(subId);
    RETURN_BOOL(result);
}

