<?php

/** @generate-class-entries */

// AUTOGENERATED FILE - DO NOT EDIT.
//
// This file has been automatically generated by FrankenPHP extension generator
// and should not be edited as it will be overwritten when running the
// extension generator again.
//
// You may edit the file and remove this comment if you plan to manually maintain
// this file going forward.

namespace Abderrahim\Nats;

/**
 * @var int
 */
const NANOSECOND = 1;

/**
 * @var int
 */
const MICROSECOND = 1000;

/**
 * @var int
 */
const MILLISECOND = 1000000;

/**
 * @var int
 */
const SECOND = 1000000000;

/**
 * @var int
 */
const MINUTE = 60000000000;

function connect(string $name, array $servers, string $username = "", string $password = "", string $token = "", string $credsFile = "", string $nkeyFile = "", bool $tls = false, int $timeout = 2000000000, int $reconnectAttempts = 60, int $reconnectWait = 2000000000, int $pingInterval = 120000000000, int $maxPingsOut = 2): void {}

function close(string $name): void {}

function isConnected(string $name): bool {}

function flush(string $name, int $timeout = 5000000000): void {}

function stats(string $name): array {}

function publish(string $name, string $subject, string $data, array $headers = []): void {}

function request(string $name, string $subject, string $data, int $timeout = 1000000000): ?array {}

function subscribe(string $name, string $subject, string $queue = ""): string {}

function unsubscribe(string $subId): void {}

function nextMessage(string $subId, int $timeout = 5000000000): ?array {}

function subscriptionValid(string $subId): bool {}


